# Change prefix to Ctrl-s (easier to reach)
# unbind C-b
# set-option -g prefix C-s
# bind-key C-s send-prefix

# Bind source file
unbind r
bind r source-file ~/.config/tmux/tmux.conf\; display "Tmux Config Reloaded!"

# Enable mouse support (scroll, click panes)
set -g mouse on

# Start window numbering at 1 (not 0)
set -g base-index 1
set -g pane-base-index 1

# Renumber when window is closed
set -g renumber-window on

set -g automatic-rename on
set -g automatic-rename-format '#{pane_current_command}'
set -g @catppuccin_window_text ' #W'
set -g @catppuccin_window_current_text ' #W'

# Move around using hjkl
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# set left and right status bar
set -g status-interval 5
set -g status-left-length 100
set -g status-right-length 100

# enable 256-colors
set -g default-terminal 'screen-256color'
set -ag terminal-overrides ',xterm-256color*:RGB'

# Catppuccin theme
run '~/.config/tmux/plugins/tmux/catppuccin.tmux'

# Status bar
set -g status-left "#{E:@catppuccin_status_session}"
set -g status-right "󰊚 #(uptime | sed 's/.*://' | xargs)  #{E:@catppuccin_status_date_time}"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)

run '~/.config/tmux/plugins/tpm/tpm'

is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h' 'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j' 'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k' 'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l' 'select-pane -R'
tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'
if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"
bind-key -n 'C-Space' if-shell "$is_vim" 'send-keys C-Space' 'select-pane -t:.+'

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l
bind-key -T copy-mode-vi 'C-Space' select-pane -t:.+

bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded config."

set-window-option -g mode-keys vi

unbind [
bind Escape copy-mode

bind-key -Tcopy-mode-vi 'v' send -X begin-selection
bind-key -Tcopy-mode-vi 'y' send -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"
bind-key -Tcopy-mode-vi Escape send -X cancel
bind-key -Tcopy-mode-vi V send -X rectangle-toggle

bind s split-window -v
bind v split-window -h

# Shift-arrows to resize panes
bind-key -n "M-Left" resize-pane -L 2
bind-key -n "M-Right" resize-pane -R 2
bind-key -n "M-Up" resize-pane -U 2
bind-key -n "M-Down" resize-pane -D 2

bind x kill-pane
